# Generated by Django 5.1.4 on 2025-01-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('CodUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=100)),
                ('Username', models.CharField(max_length=50, unique=True)),
                ('Senha', models.CharField(max_length=50)),
                ('Grupo', models.CharField(choices=[('Administradores', 'Administradores'), ('Estudantes', 'Estudantes')], max_length=15)),
            ],
        ),
    ]
