# Generated by Django 5.1.4 on 2025-01-24 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Senha',
            field=models.CharField(max_length=256),
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respostas', models.JSONField()),
                ('acertos', models.IntegerField()),
                ('percentual_acertos', models.FloatField()),
                ('data_finalizacao', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='usuarios.usuario')),
            ],
        ),
    ]
