# Generated by Django 5.1.4 on 2025-01-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_senha_resultado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultado',
            old_name='data_finalizacao',
            new_name='data_fim',
        ),
        migrations.AddField(
            model_name='resultado',
            name='data_inicio',
            field=models.DateTimeField(default='2025-01-24 16:00:00'),
            preserve_default=False,
        ),
    ]
